### ISSUE TITLE
NPM module

### ISSUE THREAD

**Issue by calvinmetcalf** [leaflet-extras/RTree#12]
We can either try to see if @maxogden (ping) wants to update the current one, or think up a witty name for this on npm, if it's the latter case I'm thinking "arrTree"

**Comment by max-mapper** [comment]
I'm happy to transfer ownership if you are willing to maintain, I tried doing `npm owner add calvinmetcalf rtree` but got:

```
npm ERR! owner mutate Error getting user data for calvinmetcalf
npm ERR! Error: not_found missing: -/user/org.couchdb.user:calvinmetcalf
```

**Comment by calvinmetcalf** [comment]
sorry, I'm cwmma on npm, thank you.

**Comment by max-mapper** [comment]
cool. done!

**Comment by calvinmetcalf** [comment]
well that solves that one, thanks @maxogden.
