### ISSUE TITLE
IE7/8 support

### ISSUE THREAD

**Issue by mtoonen** [leaflet-extras/RTree#23]
I noticed references to JSON.parse and JSON.stringify, which are not available on IE7 and 8. Which kind of browsers do you intent to support?

**Comment by calvinmetcalf** [comment]
it is available in ie8 which is as far back as I intend to support

**Comment by mtoonen** [comment]
Unfortunately, it is not :(.
From debugger in IE8.

> JSON.parse()
>  "'JSON' is undefined"

**Comment by calvinmetcalf** [comment]
document needs to be in standards mode for ie8 not quirks mode

**Comment by mtoonen** [comment]
Whoops, sorry, overlooked that one. Thanks!
