### ISSUE TITLE
Pass GeoJSON feature to rtree.geoJSON fails

### ISSUE THREAD

**Issue by mtoonen** [leaflet-extras/RTree#24]
When passing a single geojson feature to the rtree, it fails with the message "this isn\'t what we\'re looking for".
I propose a patch which checks if 'prelim' is an Object. If so, we expect it to be a single feature, and then we put it in an Array, so it fits in the rest of the code nicely. Would that be acceptable? If so, how to clone (see #23): Do I implement a pure javascript clone function, or JSON.parse(JSON.stringify(prelim))? See http://heyjavascript.com/4-creative-ways-to-clone-objects/. I would be happy to contribute this patch.
The patch I proposed yesterday I did in lib/rtree.js because I assumed dist/rtree.min.js and dist/rtree.js are build from there. Was that correct?

**Comment by calvinmetcalf** [comment]
you can probably replace the error with with `features = [prelim];`
