### ISSUE TITLE
Comparison with rbush?

### ISSUE THREAD

**Issue by twpayne** [leaflet-extras/RTree#26]
The README.md says that is is a port of [Jon-Carlos Rivera's library](https://github.com/imbcmdth/RTree). We used Jon-Carlos's RTree library in OpenLayers 3, but found that @mourner's [rbush](https://github.com/mourner/rbush) was much, much better. Compare the two screenshots below: the first is RTree, the second is rbush:
![rtree](https://f.cloud.github.com/assets/6942/1654425/2a5d3db8-5b4c-11e3-9e15-716899811f10.png)
![rbush](https://f.cloud.github.com/assets/6942/1654426/2ce21f9a-5b4c-11e3-817d-18a02c0ab9a6.png)
If this library is based on RTree, you may wish to consider switching to rbush.

**Comment by calvinmetcalf** [comment]
This repo is aimed at cleaning up some bugs in a well used but abandoned rtree implementation. Overall though it's well tested in production and GeoJSON support is the one and only feature I plan on adding.  

@mourner's rbush is a separate effort to write something similar from scratch, though I believe it is an r*-tree not an r-tree.  I've been following it keenly and if performance is your goal by all means use it, I believe it is still in development though (though knowing @mourner, it's probably very stable) so if stability is value over speed then right now this library might be a better fit, though in a few months who knows. 

If I was was making a mapping app I'd probably use rbush, I'd take a pull request to put a link to rbush in the readme.

**Comment by mourner** [comment]
@calvinmetcalf I was inspired by your work on modernizing the old RTree in this repo before I wrote RBush, maybe I wouldn't make my own attempt without yours, so cheers! :+1: Baked-in GeoJSON support is a great idea too — it would be awesome to consider creating a similar extension for RBush. 

Re R_-tree vs R-tree, — RBush uses a [mixed approach](https://github.com/mourner/rbush#algorithms-used) — initially I wrote a full R_-tree implementation (you can trace this in commit history), but then found out that many of its parts are optimized for disk access and don't make sense in "all data in memory" use case in JS, actually making things much slower, so I simplified it significantly.

@twpayne I love this visualization. Simply awesome.

**Comment by calvinmetcalf** [comment]
@mourner you just might get geojson support if get around to adding saved views to [geopouch](https://github.com/pouchdb/geopouch)

**Comment by mourner** [comment]
@twpayne the reason viz looks so much better is because of the node splitting heuristic — in R_-tree, it's optimized for topologic use cases (while other splitting algorithms might be better suited for other types of data) — screenshots here demonstate this well http://en.wikipedia.org/wiki/R__tree

**Comment by twpayne** [comment]
Thanks for the replies @calvinmetcalf and @mourner.
